server:
  port: 4000
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update